Repository fastcampus-711/backend, pull requests merged in 2024-05, with the labels that each got.

#20 공통 게시판 구현
  build.gradle
  doc/Domain.drawio
  doc/Untitled Diagram.drawio
  doc/도메인 분석.png
  src/main/java/com/aptner/v3/board/category/ApplicationContextHolder.java
  src/main/java/com/aptner/v3/board/category/CategoryName.java
  src/main/java/com/aptner/v3/board/category/controller/CategoryController.java
  src/main/java/com/aptner/v3/board/category/domain/Category.java
  src/main/java/com/aptner/v3/board/category/dto/CreateCategoryDto.java
  src/main/java/com/aptner/v3/board/category/dto/DeleteCategoryDto.java
  src/main/java/com/aptner/v3/board/category/dto/UpdateCategoryDto.java
  src/main/java/com/aptner/v3/board/category/repository/CategoryRepository.java
  src/main/java/com/aptner/v3/board/category/service/CategoryService.java
  src/main/java/com/aptner/v3/board/comment/CommentRepository.java
  src/main/java/com/aptner/v3/board/comment/controller/CommentController.java
  src/main/java/com/aptner/v3/board/comment/domain/Comment.java
  src/main/java/com/aptner/v3/board/comment/dto/CommentDto.java
  src/main/java/com/aptner/v3/board/comment/service/CommentService.java
  src/main/java/com/aptner/v3/board/common_post/controller/CommonPostController.java
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
  src/main/java/com/aptner/v3/board/common_post/repository/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/service/CommonPostService.java
  src/main/java/com/aptner/v3/board/free_board_post/controller/FreeBoardPostController.java
  src/main/java/com/aptner/v3/board/free_board_post/domain/FreeBoardPost.java
  src/main/java/com/aptner/v3/board/free_board_post/dto/FreeBoardPostDto.java
  src/main/java/com/aptner/v3/board/menu/controller/MenuController.java
  src/main/java/com/aptner/v3/board/menu/domain/Menu.java
  src/main/java/com/aptner/v3/board/menu/dto/CreateMenuDto.java
  src/main/java/com/aptner/v3/board/menu/dto/DeleteMenuDto.java
  src/main/java/com/aptner/v3/board/menu/dto/UpdateMenuDto.java
  src/main/java/com/aptner/v3/board/menu/repository/MenuRepository.java
  src/main/java/com/aptner/v3/board/menu/service/MenuService.java
  src/main/java/com/aptner/v3/board/notice_post/controller/NoticePostPostController.java
  src/main/java/com/aptner/v3/board/notice_post/domain/NoticePost.java
  src/main/java/com/aptner/v3/board/notice_post/dto/NoticePostDto.java
  src/main/java/com/aptner/v3/board/notice_post/service/NoticePostService.java
  src/main/java/com/aptner/v3/global/domain/CreatedInfo.java
  src/main/java/com/aptner/v3/global/error/ErrorCode.java
  src/main/java/com/aptner/v3/global/exception/custom/AlreadyExistsCategoryNameException.java
  src/main/java/com/aptner/v3/global/exception/custom/InvalidTableIdException.java
  src/main/java/com/aptner/v3/global/exception/custom/InvalidURIException.java
  src/main/java/com/aptner/v3/global/exception/custom/NotExistsCategoryIdException.java
  src/main/java/com/aptner/v3/global/exception/custom/NotExistsMenuIdException.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/test/java/com/aptner/v3/board/category/controller/CategoryControllerTest.java
Labels: enhancement

#46 공통 게시판 기능 구현
  src/main/java/com/aptner/v3/board/category/Category.java
  src/main/java/com/aptner/v3/board/category/CategoryCode.java
  src/main/java/com/aptner/v3/board/category/CategoryController.java
  src/main/java/com/aptner/v3/board/comment/domain/Comment.java
  src/main/java/com/aptner/v3/board/common_post/controller/CommonPostController.java
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
  src/main/java/com/aptner/v3/board/common_post/repository/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/service/CommonPostService.java
  src/main/java/com/aptner/v3/board/complain/Complain.java
  src/main/java/com/aptner/v3/board/complain/ComplainController.java
  src/main/java/com/aptner/v3/board/complain/ComplainService.java
  src/main/java/com/aptner/v3/board/complain/dto/ComplainDto.java
  src/main/java/com/aptner/v3/board/free_post/controller/FreePostController.java
  src/main/java/com/aptner/v3/board/free_post/domain/FreePost.java
  src/main/java/com/aptner/v3/board/free_post/dto/FreePostDto.java
  src/main/java/com/aptner/v3/board/market/Market.java
  src/main/java/com/aptner/v3/board/market/MarketController.java
  src/main/java/com/aptner/v3/board/market/MarketService.java
  src/main/java/com/aptner/v3/board/market/dto/MarketDto.java
  src/main/java/com/aptner/v3/board/notice_post/controller/NoticePostPostController.java
  src/main/java/com/aptner/v3/board/notice_post/dto/NoticePostDto.java
  src/main/java/com/aptner/v3/board/qna/Qna.java
  src/main/java/com/aptner/v3/board/qna/QnaController.java
  src/main/java/com/aptner/v3/board/qna/QnaService.java
  src/main/java/com/aptner/v3/board/qna/dto/QnaDto.java
  src/main/java/com/aptner/v3/global/config/SecurityConfig.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
Labels: enhancement

#43 Feature/#36 jwt refreshtoken api
  src/main/java/com/aptner/v3/MenuInitializer.java
  src/main/java/com/aptner/v3/attach/controller/AttachController.java
  src/main/java/com/aptner/v3/attach/service/ProfileService.java
  src/main/java/com/aptner/v3/global/config/SecurityConfig.java
  src/main/java/com/aptner/v3/global/jwt/CustomLogoutFilter.java
  src/main/java/com/aptner/v3/global/jwt/JwtFilter.java
  src/main/java/com/aptner/v3/global/jwt/JwtUtil.java
  src/main/java/com/aptner/v3/global/jwt/LoginFilter.java
  src/main/java/com/aptner/v3/security/dto/CustomUserDetailsDto.java
  src/main/java/com/aptner/v3/security/service/CustomUserDetailsService.java
  src/main/java/com/aptner/v3/user/User.java
  src/main/java/com/aptner/v3/user/UserRepository.java
  src/main/java/com/aptner/v3/user/UserRole.java
  src/main/java/com/aptner/v3/user/controller/UserController.java
  src/main/java/com/aptner/v3/user/domain/User.java
  src/main/java/com/aptner/v3/user/domain/UserEntity.java
  src/main/java/com/aptner/v3/user/dto/UserDto.java
  src/main/java/com/aptner/v3/user/repository/SignUpUserRepository.java
  src/main/java/com/aptner/v3/user/repository/UserDetailsRepository.java
  src/main/java/com/aptner/v3/user/repository/UserRepository.java
  src/main/java/com/aptner/v3/user/service/UserService.java
  src/main/java/com/aptner/v3/user/type/UserRole.java
Labels: develop

#52 [공통게시판] 댓글 CRUD
  src/main/java/com/aptner/v3/board/category/CategoryCode.java
  src/main/java/com/aptner/v3/board/comment/controller/CommentController.java
  src/main/java/com/aptner/v3/board/comment/domain/Comment.java
  src/main/java/com/aptner/v3/board/comment/dto/CommentDto.java
  src/main/java/com/aptner/v3/board/comment/service/CommentService.java
  src/main/java/com/aptner/v3/board/common_post/controller/CommonPostController.java
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
  src/main/java/com/aptner/v3/board/common_post/repository/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/service/CommonPostService.java
  src/main/java/com/aptner/v3/board/notice_post/controller/NoticePostController.java
  src/main/java/com/aptner/v3/board/notice_post/domain/NoticePost.java
  src/main/resources/data.sql
Labels: enhancement

#53 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#58 feature: 게시판 및 댓글 좋아요, 싫어요 기능
  src/main/java/com/aptner/v3/CommunityApplication.java
  src/main/java/com/aptner/v3/auth/dto/CustomUserDetails.java
  src/main/java/com/aptner/v3/board/comment/domain/Comment.java
  src/main/java/com/aptner/v3/board/comment/dto/CommentDto.java
  src/main/java/com/aptner/v3/board/comment/service/CommentService.java
  src/main/java/com/aptner/v3/board/common/reaction/ReactionController.java
  src/main/java/com/aptner/v3/board/common/reaction/ReactionRepository.java
  src/main/java/com/aptner/v3/board/common/reaction/domain/CommentReaction.java
  src/main/java/com/aptner/v3/board/common/reaction/domain/PostReaction.java
  src/main/java/com/aptner/v3/board/common/reaction/domain/Reaction.java
  src/main/java/com/aptner/v3/board/common/reaction/domain/ReactionColumns.java
  src/main/java/com/aptner/v3/board/common/reaction/dto/ReactionDto.java
  src/main/java/com/aptner/v3/board/common/reaction/dto/ReactionTarget.java
  src/main/java/com/aptner/v3/board/common/reaction/dto/ReactionType.java
  src/main/java/com/aptner/v3/board/common/reaction/service/CommentReactionService.java
  src/main/java/com/aptner/v3/board/common/reaction/service/PostReactionService.java
  src/main/java/com/aptner/v3/board/common/reaction/service/ReactionApplyService.java
  src/main/java/com/aptner/v3/board/common/reaction/service/ReactionService.java
  src/main/java/com/aptner/v3/board/common_post/controller/CommonPostController.java
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/board/common_post/domain/SortType.java
  src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
  src/main/java/com/aptner/v3/board/common_post/repository/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/service/CommonPostService.java
  src/main/java/com/aptner/v3/global/domain/BaseTimeEntity.java
  src/main/java/com/aptner/v3/global/error/ErrorCode.java
  src/main/java/com/aptner/v3/global/error/SuccessCode.java
  src/main/java/com/aptner/v3/global/exception/ReactionException.java
  src/main/java/com/aptner/v3/global/util/MemberUtil.java
  src/main/java/com/aptner/v3/global/util/ModelMapperUtil.java
  src/main/resources/data.sql
  src/test/java/com/aptner/v3/board/common/reaction/ReactionServiceTest.java
  src/test/resources/application.yaml
Labels: enhancement

#64 [#61-user-api] 토큰 발급 & 재발급 Token 1시간 이내 재발급
  src/main/java/com/aptner/v3/CommunityApplication.java
  src/main/java/com/aptner/v3/MenuInitializer.java
  src/main/java/com/aptner/v3/attach/controller/AttachController.java
  src/main/java/com/aptner/v3/attach/service/AttachService.java
  src/main/java/com/aptner/v3/attach/service/Impl/DBServiceImpl.java
  src/main/java/com/aptner/v3/attach/service/Impl/S3ServiceImpl.java
  src/main/java/com/aptner/v3/attach/service/ProfileService.java
  src/main/java/com/aptner/v3/attach/service/S3Service.java
  src/main/java/com/aptner/v3/auth/RefreshToken.java
  src/main/java/com/aptner/v3/auth/controller/AuthController.java
  src/main/java/com/aptner/v3/auth/dto/LoginDto.java
  src/main/java/com/aptner/v3/auth/repository/RedisRefreshTokenRepository.java
  src/main/java/com/aptner/v3/auth/repository/RefreshTokenRepository.java
  src/main/java/com/aptner/v3/auth/service/AuthService.java
  src/main/java/com/aptner/v3/board/free_post/controller/FreePostController.java
  src/main/java/com/aptner/v3/global/config/JpaConfig.java
  src/main/java/com/aptner/v3/global/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/aptner/v3/global/config/RedisConfig.java
  src/main/java/com/aptner/v3/global/config/S3ClientConfig.java
  src/main/java/com/aptner/v3/global/config/SecurityConfig.java
  src/main/java/com/aptner/v3/global/config/SwaggerConfig.java
  src/main/java/com/aptner/v3/global/error/ErrorCode.java
  src/main/java/com/aptner/v3/global/exception/AuthException.java
  src/main/java/com/aptner/v3/global/exception/GlobalException.java
  src/main/java/com/aptner/v3/global/exception/GlobalExceptionHandler.java
  src/main/java/com/aptner/v3/global/exception/JwtAccessDeniedHandler.java
  src/main/java/com/aptner/v3/global/jwt/JwtFilter.java
  src/main/java/com/aptner/v3/global/util/JwtUtil.java
  src/main/java/com/aptner/v3/global/util/ResponseUtil.java
  src/main/java/com/aptner/v3/member/controller/MemberController.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/test/java/com/aptner/v3/auth/service/AuthServiceTest.java
  src/test/java/com/aptner/v3/global/ApiResponseTest.java
  src/test/java/com/aptner/v3/global/util/JwtUtilTest.java
  src/test/java/com/aptner/v3/menu/MenuJpaTest.java
  src/test/resources/application.yaml
Labels: enhancement

#63 [#59-commonPost-api] 분류선택 게시판 기능 구현
  src/main/java/com/aptner/v3/board/common_post/controller/CommonPostController.java
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
  src/main/java/com/aptner/v3/board/common_post/repository/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/service/CommonPostService.java
  src/main/java/com/aptner/v3/board/free_post/FreePostService.java
  src/main/resources/data.sql
Labels: develop

#69 feat & refactor: 자잘한 리펙토링 + 공감,댓글개수 api 연관관계 조정
  build.gradle
  src/main/java/com/aptner/v3/board/category/CategoryCode.java
  src/main/java/com/aptner/v3/board/comment/Comment.java
  src/main/java/com/aptner/v3/board/comment/CommentDto.java
  src/main/java/com/aptner/v3/board/comment/CommentService.java
  src/main/java/com/aptner/v3/board/common/reaction/domain/Reaction.java
  src/main/java/com/aptner/v3/board/common/reaction/domain/ReactionColumns.java
  src/main/java/com/aptner/v3/board/common/reaction/dto/CountOfReactionTypeDto.java
  src/main/java/com/aptner/v3/board/common/reaction/service/CommentReactionService.java
  src/main/java/com/aptner/v3/board/common/reaction/service/CountOfReactionAndCommentApplyService.java
  src/main/java/com/aptner/v3/board/common/reaction/service/PostReactionService.java
  src/main/java/com/aptner/v3/board/common/reaction/service/ReactionAndCommentCalculator.java
  src/main/java/com/aptner/v3/board/common/reaction/service/ReactionService.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostController.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostDto.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostService.java
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
  src/main/java/com/aptner/v3/board/complain/ComplainController.java
  src/main/java/com/aptner/v3/board/complain/ComplainService.java
  src/main/java/com/aptner/v3/board/complain/dto/ComplainDto.java
  src/main/java/com/aptner/v3/board/free_post/FreePostService.java
  src/main/java/com/aptner/v3/board/free_post/controller/FreePostController.java
  src/main/java/com/aptner/v3/board/free_post/dto/FreePostDto.java
  src/main/java/com/aptner/v3/board/market/MarketController.java
  src/main/java/com/aptner/v3/board/market/MarketService.java
  src/main/java/com/aptner/v3/board/market/dto/MarketDto.java
  src/main/java/com/aptner/v3/board/notice_post/controller/NoticePostController.java
  src/main/java/com/aptner/v3/board/notice_post/dto/NoticePostDto.java
  src/main/java/com/aptner/v3/board/qna/QnaController.java
  src/main/java/com/aptner/v3/board/qna/QnaService.java
  src/main/java/com/aptner/v3/board/qna/dto/QnaDto.java
  src/main/java/com/aptner/v3/global/exception/JwtAccessDeniedHandler.java
  src/main/java/com/aptner/v3/global/util/MemberUtil.java
  src/main/java/com/aptner/v3/global/util/ModelMapperUtil.java
  src/main/resources/data.sql
  src/test/java/com/aptner/v3/board/common/reaction/ReactionServiceTest.java
  src/test/java/com/aptner/v3/board/common_post/CommonPostTest.java
  src/test/java/com/aptner/v3/board/common_post/service/BlindPostAndCommentTest.java
  src/test/java/com/aptner/v3/board/common_post/service/CommonPostServiceCountOfCommentsApplyTest.java
Labels: improvement

#56 Feature/#47 attach api
  src/main/java/com/aptner/v3/board/free_post/FreePostService.java
  src/main/java/com/aptner/v3/board/free_post/controller/FreePostController.java
  src/main/java/com/aptner/v3/board/free_post/domain/FreePost.java
  src/main/java/com/aptner/v3/board/free_post/dto/FreePostDto.java
  src/main/java/com/aptner/v3/board/market/Market.java
  src/main/java/com/aptner/v3/board/market/MarketController.java
  src/main/java/com/aptner/v3/board/market/MarketService.java
  src/main/java/com/aptner/v3/board/market/dto/MarketDto.java
  src/main/java/com/aptner/v3/board/notice_post/NoticePostService.java
  src/main/java/com/aptner/v3/board/notice_post/controller/NoticePostController.java
  src/main/java/com/aptner/v3/board/notice_post/domain/NoticePost.java
  src/main/java/com/aptner/v3/board/notice_post/dto/NoticePostDto.java
  src/test/java/com/aptner/v3/board/common_post/service/CommonPostServiceCountOfCommentsApplyTest.java
Labels: develop

#70 Feature/#57 popular post api
  build.gradle
  src/main/java/com/aptner/v3/board/comment/CommentController.java
  src/main/java/com/aptner/v3/board/common/reaction/service/ReactionService.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostController.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostService.java
  src/main/java/com/aptner/v3/board/common_post/dto/CommonPostDto.java
  src/main/java/com/aptner/v3/global/config/SchedulingConfig.java
  src/main/java/com/aptner/v3/global/config/SecurityConfig.java
  src/main/resources/data.sql
  src/test/java/com/aptner/v3/board/common_post/service/BlindPostAndCommentTest.java
  src/test/java/com/aptner/v3/board/common_post/service/CommonPostServiceCountOfCommentsApplyTest.java
Labels: develop

#73 공통 게시판 테스트 코드 작성 및 과정 중 Issue 해결
  build.gradle
  src/main/java/com/aptner/v3/board/category/CategoryCode.java
  src/main/java/com/aptner/v3/board/comment/Comment.java
  src/main/java/com/aptner/v3/board/comment/CommentDto.java
  src/main/java/com/aptner/v3/board/comment/CommentService.java
  src/main/java/com/aptner/v3/board/common/reaction/domain/ReactionColumns.java
  src/main/java/com/aptner/v3/board/common/reaction/service/CountCommentsAndReactionApplyService.java
  src/main/java/com/aptner/v3/board/common/reaction/service/ReactionService.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostController.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostDto.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostService.java
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/board/free_post/FreePostService.java
  src/main/java/com/aptner/v3/board/free_post/controller/FreePostController.java
  src/main/java/com/aptner/v3/board/free_post/domain/FreePost.java
  src/main/java/com/aptner/v3/board/free_post/dto/FreePostDto.java
  src/main/java/com/aptner/v3/board/market/MarketController.java
  src/main/java/com/aptner/v3/board/notice_post/NoticePostService.java
  src/main/java/com/aptner/v3/board/notice_post/controller/NoticePostController.java
  src/main/java/com/aptner/v3/board/notice_post/domain/NoticePost.java
  src/main/java/com/aptner/v3/board/notice_post/dto/NoticePostDto.java
  src/main/java/com/aptner/v3/global/config/SecurityConfig.java
  src/main/java/com/aptner/v3/global/error/ErrorCode.java
  src/main/java/com/aptner/v3/global/exception/PostException.java
  src/main/java/com/aptner/v3/global/util/MemberUtil.java
  src/main/java/com/aptner/v3/global/util/ModelMapperUtil.java
  src/main/resources/data.sql
  src/test/java/com/aptner/v3/board/common/reaction/ReactionServiceTest.java
  src/test/java/com/aptner/v3/board/common_post/CommonPostControllerTest.java
  src/test/java/com/aptner/v3/board/common_post/CommonPostTest.java
  src/test/java/com/aptner/v3/board/common_post/service/BlindPostAndCommentTest.java
  src/test/java/com/aptner/v3/board/common_post/service/CommonPostServiceCountOfCommentsApplyTest.java
Labels: improvement

#90 feat: 기획에 맞게 댓글 api 수정
  src/main/java/com/aptner/v3/board/comment/Comment.java
  src/main/java/com/aptner/v3/board/comment/CommentDto.java
  src/main/java/com/aptner/v3/board/comment/CommentService.java
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/global/util/ModelMapperUtil.java
  src/main/resources/data.sql
  src/test/java/com/aptner/v3/board/common/reaction/ReactionServiceTest.java
  src/test/java/com/aptner/v3/board/common_post/service/BlindPostAndCommentTest.java
  src/test/java/com/aptner/v3/board/common_post/service/CommonPostServiceCountOfCommentsApplyTest.java
Labels: improvement
