Repository fastcampus-711/backend, pull requests merged in 2024-06, with the labels that each got.

#103 Feature/#85 update market api
  src/main/java/com/aptner/v3/board/common_post/CommonPostDto.java
  src/main/java/com/aptner/v3/board/common_post/CommonPostRepository.java
  src/main/java/com/aptner/v3/board/common_post/service/CommonPostService.java
  src/main/java/com/aptner/v3/board/complain/dto/ComplainDto.java
  src/main/java/com/aptner/v3/board/market/Market.java
  src/main/java/com/aptner/v3/board/market/MarketRepository.java
  src/main/java/com/aptner/v3/board/market/MarketService.java
  src/main/java/com/aptner/v3/board/market/MarketStatus.java
  src/main/java/com/aptner/v3/board/market/dto/MarketDto.java
  src/main/java/com/aptner/v3/board/notice_post/domain/NoticePost.java
  src/main/java/com/aptner/v3/board/notice_post/dto/NoticePostDto.java
  src/main/java/com/aptner/v3/board/qna/Qna.java
Labels: develop, improvement

#108 [feature/#107-update-dataSQL] update data.sql
  src/main/resources/data.sql
Labels: hotfix

#114 [feature/#107-market-data-add] data.sql categoryId 매칭
  src/main/resources/data.sql
Labels: hotfix

#118 [관리비 조회] 관리비 조회 1차 개발 완료
  build.gradle
  src/main/java/com/aptner/v3/global/error/ErrorCode.java
  src/main/java/com/aptner/v3/global/error/SuccessCode.java
  src/main/java/com/aptner/v3/global/exception/custom/InValidHouseIdException.java
  src/main/java/com/aptner/v3/global/exception/custom/InValidUserInfoException.java
  src/main/java/com/aptner/v3/global/exception/custom/UnreadableFileException.java
  src/main/java/com/aptner/v3/maintenance_bill/MaintenanceBillBatchService.java
  src/main/java/com/aptner/v3/maintenance_bill/MaintenanceBillController.java
  src/main/java/com/aptner/v3/maintenance_bill/MaintenanceBillService.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/House.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/HouseAverageMaintenanceFee.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/HouseAverageMaintenanceFeePrimaryKeys.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/MaintenanceBill.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/MaintenanceBillMonthlyStatic.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/MaintenanceBillPrimaryKeys.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/type/EnergyType.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/type/HouseType.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/type/ResidentType.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/type/residenceType.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill/EnergyUsageDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill/FareCollectionDiscountDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill/FareCollectionFeeDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill/HouseDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill/MaintenanceBillDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill/MaintenanceBillPrimaryKeysDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill/SubMaintenanceFeeDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/CircularChartDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/EnergyUsageDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/MaintenanceBillMonthlyStaticDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/MaintenanceBillPrimaryKeys.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/MaintenanceBillSummaryDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/MonthOnMonthInfoDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/SquareOnSquareInfoDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/YearOnYearInfoDto.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill/EnergyUsage.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill/FareCollectionDiscount.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill/FareCollectionFee.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill/ResidentInfo.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill/SubMaintenanceFee.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill_monthly_static/CircularChart.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill_monthly_static/EnergyUsage.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill_monthly_static/MaintenanceBillSummary.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill_monthly_static/MonthOnMonthInfo.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill_monthly_static/SquareOnSquareInfo.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill_monthly_static/YearOnYearInfo.java
  src/main/java/com/aptner/v3/maintenance_bill/excel_util/ExcelColumn.java
  src/main/java/com/aptner/v3/maintenance_bill/mapper/HouseMapper.java
  src/main/java/com/aptner/v3/maintenance_bill/mapper/MaintenanceBillMapper.java
  src/main/java/com/aptner/v3/maintenance_bill/mapper/MaintenanceBillMonthlyStaticMapper.java
  src/main/java/com/aptner/v3/maintenance_bill/repository/HouseAverageMaintenanceFeeRepository.java
  src/main/java/com/aptner/v3/maintenance_bill/repository/HouseRepository.java
  src/main/java/com/aptner/v3/maintenance_bill/repository/MaintenanceBillMonthlyStaticRepository.java
  src/main/java/com/aptner/v3/maintenance_bill/repository/MaintenanceBillRepository.java
  src/main/java/com/aptner/v3/member/Member.java
  src/main/java/com/aptner/v3/member/repository/MemberRepository.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/main/resources/maintenance-bill.sql
  src/test/resources/application.yaml
Labels: enhancement

#128 refactor: 관리비 Response 개선
  src/main/java/com/aptner/v3/maintenance_bill/MaintenanceBillService.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/MaintenanceBillSummaryDto.java
  src/main/java/com/aptner/v3/maintenance_bill/dto/maintenance_bill_monthly_static/SquareOnSquareInfoDto.java
Labels: develop

#133 검색어 -> 인기 게시글 같이 노출 (해결 완료)
  src/main/java/com/aptner/v3/board/common_post/domain/CommonPost.java
  src/main/java/com/aptner/v3/board/free_post/FreePostService.java
  src/main/java/com/aptner/v3/board/market/dto/MarketDto.java
  src/main/java/com/aptner/v3/board/qna/dto/QnaDto.java
Labels: bug

#135 ëqna 삭제 오류
  src/main/java/com/aptner/v3/board/qna/QnaController.java
Labels: bug

#139 Swagger naming
  src/main/java/com/aptner/v3/MenuInitializer.java
  src/main/java/com/aptner/v3/global/jwt/JwtFilter.java
  src/main/java/com/aptner/v3/global/util/MemberUtil.java
  src/main/java/com/aptner/v3/maintenance_bill/MaintenanceBillController.java
  src/main/java/com/aptner/v3/maintenance_bill/domain/House.java
  src/main/java/com/aptner/v3/maintenance_bill/embed/maintenance_bill/ResidentInfo.java
  src/main/java/com/aptner/v3/member/Member.java
  src/main/resources/data.sql
Labels: documentation
